apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- clusterrole.yaml
- clusterrole_binding.yaml
- service_account.yaml
- deployment.yaml
- service.yaml
- namespace-istio-system.yaml
